### ISSUE TITLE
MRI_Root_Hair_Tools

### ISSUE THREAD

**Issue by Sandae33** [MontpellierRessourcesImagerie/imagej_macros_and_scripts#11]
Dear Volker,

I am currently experimenting with the MRI_Root_Hair_Tools. 
I have however trouble running it with the test pictures: 

While using the first picture (the second one is just black) with the recommended values I get the error: 

![Unbenannt](https://user-images.githubusercontent.com/104084988/164258602-e48470fd-8381-47fa-875d-5da0eac97973.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/104084988/164258886-fbeda3b8-0ebc-4716-9dac-9ba688eb1b4b.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/104084988/164258894-2110fabb-d694-4e91-86e9-9ab2ad2d3055.PNG)

I understand that the application is from 2018, but maybe you can still help me. 

Thank you for your time and best wishes

**Comment by volker-baecker** [comment]
Hi @Sandae33,
I fixed some issues due to changes in ImageJ since 2017 :) Please try with the new version. I also changed the parameter values that should work on the example images.
Best,
Volker

**Comment by volker-baecker** [comment]
By the way, the other test image is not all black. It is a 16-bit image with most of the intensity values in the lower range. When you open it with ImageJ you should see something. If not it should be enough to adjust the brightness/contrast.

**Comment by Sandae33** [comment]
Hello Volker,

Thank you for your answer and help! I tried it again with the new version and parameters, but there seems to be a problem:

![Unbenannt](https://user-images.githubusercontent.com/104084988/165043167-d53aa2e1-85dd-403e-8b51-7389dcc1f6fc.png)
![Unbenannt1](https://user-images.githubusercontent.com/104084988/165043176-32b7f0d7-f28c-4555-b74e-e388a6ae82bc.PNG)

Sadly I'm not really sure what the mistake is. 

And the problem with the second Pic was my fault, did not open it in ImageJ ;). 

Best wishes!

**Comment by volker-baecker** [comment]
Hi @Sandae33,
yes, I'm sorry. I confused the options for the first and the second image. I corrected it on the help page. The options for the first image are:
5, 500, 500, unselected, unselected, "IsoData", unselected 
Best,
Volker

**Comment by Sandae33** [comment]
Hi,

Now it works. Thank you very much and have a nice day!
