### ISSUE TITLE
Error Message for 'f' function

### ISSUE THREAD

**Issue by taylor-mtt** [MontpellierRessourcesImagerie/imagej_macros_and_scripts#14]
Hello,

This tool is super helpful but I have a few issues with it. I am wondering 1) how can I edit the individual axon diameters, as they are accurate about 70% of the time but many require small adjustments. I tried using the brush tool but it's not working for me, I think I'm missing something. And 2) the 'f' function in the macro (to measure myelin diameter /outer diameter) is not working for me at all. Each time I try to use it I get the same error message, attached here. I followed the installation instructions exactly. Is there some updated version of the macro? 

Thanks so much for your help,
Taylor
![wt sciatic error](https://user-images.githubusercontent.com/108135718/175546579-14ed6a01-be9d-44d7-b472-eed5c54763cd.jpg)

**Comment by volker-baecker** [comment]
Hi @taylor-mtt,
thanks for your interest in our tool.
Yes you can use the brush tool. First click on the label of the ROI you want to correct. That will select the ROI in the roi-manager and create an active ROI on the image. Now use the brush or any other selection-tool to modify the active roi (it probably has a different color, depending on your settings). When done press the update-button on the roi-manager.
If you are using the procedure as described and still have problems, please let me know.

The error message indicates that you are using an old version of ImageJ/FIJI, that does not know the Table commands. Please update to the latest version and try again.

Best,
Volker
