### ISSUE TITLE
Intensity_Ratio_Nuclei_Cytoplasm.ijm

### ISSUE THREAD

**Issue by PVSeegren** [MontpellierRessourcesImagerie/imagej_macros_and_scripts#17]
Hello, 

I wanted to try your tool to automate some of my image analysis, however I am unable to download the toolset from the link on your page. 

Thanks

**Comment by volker-baecker** [comment]
Hi @PVSeegren,

It works for me (from home). What is exactly happening when you try? You are using this link
[Intensity_Ratio_Nuclei_Cytoplasm.ijm)](http://dev.mri.cnrs.fr/attachments/download/1931/Intensity_Ratio_Nuclei_Cytoplasm.ijm)
from this page: 
[Intensity-Ratio-Nuclei-Cytoplasm-Tool](https://github.com/MontpellierRessourcesImagerie/imagej_macros_and_scripts/wiki/Intensity-Ratio-Nuclei-Cytoplasm-Tool) ?
Best,
Volker
