### ISSUE TITLE
problems with Foci Per Nucleus Tool

### ISSUE THREAD

**Issue by lanternx** [MontpellierRessourcesImagerie/imagej_macros_and_scripts#3]
When I use "b" button to run with a fold, I get a fold named out. 
I want to know the meaning of images in it count for.

**Comment by lanternx** [comment]
Also, I have trouble for matching the nuclei index with the nuclei, since I want to manually screen out inappropriate nuclei according to other fluorescent image.

**Comment by volker-baecker** [comment]
> When I use "b" button to run with a fold, I get a fold named out.
> I want to know the meaning of images in it count for.

I'm not sure to understand what you mean. Can you please try to reformulate this. In the results tables (Foci, Nuclei) I get the names of the images not of the folder.

![image](https://user-images.githubusercontent.com/7602420/88641860-0b4b3d80-d0c0-11ea-9d25-d13978a1fd30.png)

**Comment by volker-baecker** [comment]
> Also, I have trouble for matching the nuclei index with the nuclei, since I want to manually screen out inappropriate nuclei according to other fluorescent image.

Can you explain the trouble you have with this? The rois of the nuclei are numbered from 1 to N in the image and you find the same numbering in the results tables.

**Comment by lanternx** [comment]
> When I use "b" button to run with a fold, I get a fold named out.
> I want to know the meaning of images in it count for.
> 
> I'm not sure to understand what you mean. Can you please try to reformulate this. In the results tables (Foci, Nuclei) I get the names of the images not of the folder.

As I haven't logged in for a long time, I didn't notice your reply. I'm sorry.

I should have noticed that nuclei are numbered by their position. So I can find what I want. 
Thank you.
