### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by JDG210** [MontpellierRessourcesImagerie/imagej_macros_and_scripts#7]
Hello,
I'm trying to run the MRI_g_ratio_Tools and when using the"f" button I have the following error message:
Error:		Undefined variable in line 153:
		<Table> . create ( title ) ; 
![image](https://user-images.githubusercontent.com/91163301/134258791-b909095a-e846-4b4a-8368-8d423ce1fa34.png)

I didn't modify the original macro.
Would you know how I could correct that issue?

Many thanks.

Best regards

**Comment by volker-baecker** [comment]
Hi @JDG210,
according to the error message 'Table' is not known. What is the version of ImageJ you are using (Help>About ImageJ...)? You might need to update your ImageJ to a recent version (Help>Update ImageJ).
Best regards,
Volker

**Comment by JDG210** [comment]
Thanks,
indeed I had the 1.51 version and updated to the 1.53, that error doesn't appear anymore.

I have another issue with the results though, I will ask in a new Issue.
