### ISSUE TITLE
missing brackets in code

### ISSUE THREAD

**Issue by svanbeuge** [MontpellierRessourcesImagerie/imagej_macros_and_scripts#9]
Code for conversion tool does not work, there are { missing throughout

**Comment by volker-baecker** [comment]
Hi, @svanbeuge 
thank you for the information. Which tool do you mean (there are multiple conversion tools)? I just tested the [Image_Conversion_Tools](https://github.com/MontpellierRessourcesImagerie/imagej_macros_and_scripts/wiki/Image_Conversion_Tools) and they worked fine.
Best,
Volker

**Comment by volker-baecker** [comment]
If you mean [
convert_Opera_To_Hyperstack.py ](https://github.com/MontpellierRessourcesImagerie/imagej_macros_and_scripts/tree/master/volker/scripts) this is a jython-script not an IJ-macro. You have to switch the language to python in the FIJI-script editor before running it.

Note that there is also a more general version here: [MRI_Convert_Opera_To_Hyperstack](https://github.com/MontpellierRessourcesImagerie/imagej_macros_and_scripts/wiki/MRI_Convert_Opera_To_Hyperstack)

and a newer tool, here:

[MRI_Opera_export_tools](https://github.com/MontpellierRessourcesImagerie/imagej_macros_and_scripts/wiki/MRI_Opera_export_tools)
